use_frameworks!

target 'NizaiiLib_Example', :exclusive => true do
  pod 'NizaiiLib', :path => '../'
end

target 'NizaiiLib_Tests', :exclusive => true do
  pod 'NizaiiLib', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
